import { Product } from "@/types";

export const products: Product[] = [
  // Tecnología
  {
    id: "1",
    nombre: "Audífonos Bluetooth Noise Cancelling",
    categoria: "Tecnología",
    precioUnitario: 250,
    precioMayor: 180,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    descripcion: "Audífonos de alta calidad con cancelación de ruido activa.",
    negociable: true,
    mayorVenta: true,
    descuento: true,
  },
  {
    id: "2",
    nombre: "Smartwatch Deportivo Pro",
    categoria: "Tecnología",
    precioUnitario: 180,
    precioMayor: 140,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    descripcion: "Smartwatch resistente al agua con monitoreo de salud.",
    negociable: true,
    mayorVenta: true,
    nuevaMarca: true,
  },
  {
    id: "6",
    nombre: "Cámara de Seguridad WiFi",
    categoria: "Tecnología",
    precioUnitario: 190,
    precioMayor: 150,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1558002038-1091773cc42f?w=800&q=80",
    descripcion: "Vigilancia 24/7 con visión nocturna y app móvil.",
    negociable: true,
    masSolicitado: true,
  },
  {
    id: "7",
    nombre: "Drone 4K Profesional",
    categoria: "Tecnología",
    precioUnitario: 1200,
    precioMayor: 1050,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=800&q=80",
    descripcion: "Drone plegable con cámara 4K, GPS y 30min de vuelo.",
    negociable: true,
    nuevoModelo: true,
  },
  {
    id: "8",
    nombre: "Proyector Portátil Mini",
    categoria: "Tecnología",
    precioUnitario: 650,
    precioMayor: 580,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    porTemporada: true,
    imagen: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&q=80",
    descripcion: "Cine en casa, compatible con HDMI y WiFi.",
    negociable: true,
    nuevoModelo: true,
    promocion: true,
  },
  {
    id: "9",
    nombre: "Teclado Mecánico RGB",
    categoria: "Tecnología",
    precioUnitario: 350,
    precioMayor: 300,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80",
    descripcion: "Switches azules, retroiluminación personalizable.",
    negociable: true,
    mayorVenta: true,
  },

  // Hogar
  {
    id: "3",
    nombre: "Juego de Sábanas de Algodón Egipcio",
    categoria: "Hogar",
    precioUnitario: 320,
    precioMayor: 280,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1522771753035-711989726f1d?w=800&q=80",
    descripcion: "Sábanas suaves y duraderas, 100% algodón.",
    negociable: true,
    interesante: true,
  },
  {
    id: "10",
    nombre: "Aspiradora Robot Inteligente",
    categoria: "Hogar",
    precioUnitario: 1500,
    precioMayor: 1350,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?w=800&q=80",
    descripcion: "Mapeo inteligente, control por app y carga automática.",
    negociable: true,
    masSolicitado: true,
  },
  {
    id: "11",
    nombre: "Freidora de Aire Digital",
    categoria: "Hogar",
    precioUnitario: 480,
    precioMayor: 420,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1626146604277-fdd20a321935?w=800&q=80",
    descripcion: "Cocina saludable sin aceite, 5.5L de capacidad.",
    negociable: true,
    nuevoModelo: true,
  },
  {
    id: "12",
    nombre: "Cafetera Expresso Italiana",
    categoria: "Hogar",
    precioUnitario: 280,
    precioMayor: 240,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    descripcion: "Diseño clásico para el café perfecto cada mañana.",
    negociable: true,
    porTemporada: true,
  },

  // Belleza
  {
    id: "4",
    nombre: "Kit de Maquillaje Profesional",
    categoria: "Belleza",
    precioUnitario: 450,
    precioMayor: 380,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1522335789203-abd6538d8ad1?w=800&q=80",
    descripcion: "Kit completo con sombras, labiales y brochas.",
    negociable: true,
    mayorVenta: true,
    combo: true,
  },
  {
    id: "13",
    nombre: "Set de Skincare Coreano",
    categoria: "Belleza",
    precioUnitario: 380,
    precioMayor: 320,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: true,
    porTemporada: true,
    imagen: "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?w=800&q=80",
    descripcion: "Rutina completa de 10 pasos para piel radiante.",
    negociable: true,
    combo: true,
  },
  {
    id: "14",
    nombre: "Secadora de Cabello Iónica",
    categoria: "Belleza",
    precioUnitario: 290,
    precioMayor: 250,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1522338242992-e1a54906a8e6?w=800&q=80",
    descripcion: "Secado rápido que protege tu cabello del frizz.",
    negociable: true,
  },

  // Accesorios
  {
    id: "5",
    nombre: "Mochila Antirrobo Impermeable",
    categoria: "Accesorios",
    precioUnitario: 120,
    precioMayor: 95,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    descripcion: "Mochila segura con puerto USB y materiales resistentes.",
    negociable: true,
    mayorVenta: true,
  },
  {
    id: "15",
    nombre: "Reloj Mecánico Automático",
    categoria: "Accesorios",
    precioUnitario: 890,
    precioMayor: 750,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
    descripcion: "Elegancia atemporal, maquinaria visible, sin pilas.",
    negociable: true,
    nuevoModelo: true,
  },
  {
    id: "16",
    nombre: "Gafas de Sol Polarizadas",
    categoria: "Accesorios",
    precioUnitario: 150,
    precioMayor: 110,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: true,
    porTemporada: true,
    imagen: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
    descripcion: "Protección UV400 con estilo moderno.",
    negociable: true,
    nuevoModelo: true,
    interesante: true,
  },
  // Nuevos productos agregados
  {
    id: "17",
    nombre: "Nintendo Switch OLED",
    categoria: "Tecnología",
    precioUnitario: 2400,
    precioMayor: 2150,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1578303512597-8198dd382374?w=800&q=80",
    descripcion: "Consola híbrida con pantalla OLED vibrante de 7 pulgadas.",
    negociable: true,
    masVendido: true, // Legacy flag just in case
    mayorVenta: true,
    promocion: true,
  },
  {
    id: "18",
    nombre: "Licuadora Profesional 1200W",
    categoria: "Hogar",
    precioUnitario: 750,
    precioMayor: 680,
    minMayor: 3,
    moneda: "Bs",
    oferta: true,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1570222094114-28a9d8894566?w=800&q=80",
    descripcion: "Trita hielo y frutas congeladas en segundos.",
    negociable: true,
    descuento: true,
  },
  {
    id: "19",
    nombre: "Perfume Elegance 100ml",
    categoria: "Belleza",
    precioUnitario: 420,
    precioMayor: 350,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    descripcion: "Fragancia floral de larga duración, importada de Francia.",
    negociable: true,
    mayorVenta: true,
  },
  {
    id: "20",
    nombre: "Maleta de Viaje Rígida",
    categoria: "Accesorios",
    precioUnitario: 550,
    precioMayor: 480,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1565026057447-bccc8c9430c8?w=800&q=80",
    descripcion: "Resistente a golpes, 4 ruedas 360° y cerradura TSA.",
    negociable: true,
    masSolicitado: true,
  },
  {
    id: "21",
    nombre: "Smartphone Foldable Z",
    categoria: "Tecnología",
    precioUnitario: 8500,
    precioMayor: 8000,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: true,
    imagen: "https://images.unsplash.com/photo-1628280650965-4f368f510860?w=800&q=80",
    descripcion: "El futuro en tus manos, pantalla plegable revolucionaria.",
    negociable: true,
    nuevoModelo: true,
  },
  {
    id: "22",
    nombre: "Lámpara de Pie Minimalista",
    categoria: "Hogar",
    precioUnitario: 450,
    precioMayor: 390,
    minMayor: 3,
    moneda: "Bs",
    oferta: false,
    arancelCero: false,
    imagen: "https://images.unsplash.com/photo-1513506003013-953a45bf4811?w=800&q=80",
    descripcion: "Iluminación cálida con diseño escandinavo moderno.",
    negociable: true,
    interesante: true,
  },
];

export async function getProducts() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500));
  return products;
}

export async function getProductById(id: string) {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return products.find((p) => p.id === id);
}

export async function getProductsByCategory(category: string) {
    await new Promise((resolve) => setTimeout(resolve, 500));
    // Simple case insenstive match
    return products.filter(p => p.categoria.toLowerCase() === category.toLowerCase());
}
